### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by AnshuTrivedi** [nextcloud/browser_warning#136]
@MorrisJobke @adsworth @SunboX 
Issue: I saw your project wanted to use application and test it but due to limited info in README i couldn't .
suggested solution: You can update  instructions how to install and use  and more clear desccription about project.

**Comment by MorrisJobke** [comment]
Most likely @skjnldsv can help here

**Comment by skjnldsv** [comment]
If you wanted to use the app, it's in the appstore :)
If you wanted to dev on it, I added steps, it's liek any other nc app :wink: 
https://github.com/nextcloud/browser_warning/blob/master/README.md#-development-setup
