### ISSUE TITLE
How/where to add own messages

### ISSUE THREAD

**Issue by moorsey** [nextcloud/browser_warning#3]
Just wondering if anyone had some steps on how to add your own messages using this app, as there is no guidance on this anywhere that I can find.

I have looked at the examples is "rules.js", but there is no info on where this lives to update once the app is installed.

Happy to add to documentation once I have my head around things

**Comment by skjnldsv** [comment]
Hey! :)
This app is not made to received custom edits my users.
Nonetheless, if you wish to compile your own, just clone this repository, edit the rules files ( see the ua-parser library for user agent match syntax)
Then compile the app with npm

```bash
npm ci
npm run build
make appstore
```

**Comment by reiner-text** [comment]
> This app is not made to received custom edits my users.

Nevertheless, the message should reflect the really reason of the warning and not displaying a bogus message.
I am using the latest version of Samsung Internet, Firefox Focus, and Vivaldi. So the message that I am `using an outdated browser` is not accurate. The device is _really outdated_ with an outdated **32-bit** Android version. The last is the real and only reason.

**Comment by skjnldsv** [comment]
@reiner-text Hey!
Feel free to open a pull request with more suitable error messages :)
Thanks!
